[build]
  command = "pip install -r requirements.txt && npm install && npm run build"
  publish = "build"
  functions = "functions"

[build.environment]
  PIPENV_VENV_IN_PROJECT = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200