"""empty message

Revision ID: c6ba5e75007d
Revises: 1edc5a71a80b
Create Date: 2023-11-28 00:30:02.249006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = 'c6ba5e75007d'
down_revision = '1edc5a71a80b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'user_username_key' in [uc['name'] for uc in inspector.get_unique_constraints('user')]:
            batch_op.drop_constraint('user_username_key', type_='unique')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_username_key', ['username'])

    # ### end Alembic commands ###
